---
# bundle exec jekyll serve

exclude:
  - .idea/
  - .gitignore

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown

### content configuration ###
title:       "Temple of the Times"
keywords:    ""
description: ""
source_link: ""
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  dgray:     '#323232'
  gray:      '#666666'
  lgray:     '#999999'
  white:     '#f8f8f8'
  dred:      '#3f0000'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false
